-- =============================================
-- Books API - Table Creation & Seed Data
-- Run this in the Supabase SQL Editor
-- =============================================

-- Create the book table
create table book (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  genre text,
  published_year integer,
  isbn text,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert sample data
insert into book (title, author, genre, published_year, isbn)
values
  ('The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction', 1925, '978-0743273565'),
  ('To Kill a Mockingbird', 'Harper Lee', 'Fiction', 1960, '978-0061120084'),
  ('1984', 'George Orwell', 'Dystopian', 1949, '978-0451524935'),
  ('Pride and Prejudice', 'Jane Austen', 'Romance', 1813, '978-0141439518'),
  ('The Catcher in the Rye', 'J.D. Salinger', 'Fiction', 1951, '978-0316769488');
